### ISSUE TITLE
reload memory usage

### ISSUE THREAD

**Issue by AdamJacobMuller** [SpiderLabs/ModSecurity#1546]
Hello,

We are running [ModSecurity@1edd3570e11e9bb2b6d86b249232b24917a4b0ac](https://github.com/SpiderLabs/ModSecurity/commit/1edd3570e11e9bb2b6d86b249232b24917a4b0ac) and [ModSecurity-nginx@abbf2c47f6f3205484a1a9db618e067dce213b89](https://github.com/SpiderLabs/ModSecurity-nginx/commits/abbf2c47f6f3205484a1a9db618e067dce213b89) with nginx 1.13.1.

I'm attaching the rule set + modsecurity configuration as well.

When reloading nginx, memory usage will *sometimes* grow exponentially and easily overwhelm the resources on the server (~100GB of ram). This does not happen 100% of the time, but, is trivial to reproduce just by doing `while true;do nginx -s reload;done`, nginx will cause the system to OOM reliably after a few minutes.

[rules.zip](https://github.com/SpiderLabs/ModSecurity/files/1250804/rules.zip)

**Comment by zimmerle** [comment]
Testing with cc1d220b408fe73a4e1950b71848772d505d6ce0. Not able to reproduce. Do you mind to shared your configuration summary?

**Comment by AdamJacobMuller** [comment]
Hi @zimmerle,

Could I share offline with you the full configuration, or just give you access to an environment where I can demonstrate it?

-Adam

**Comment by zimmerle** [comment]
Hi @AdamJacobMuller,

Sure it won't be a problem. But please, before do that, it will be very good if you can upgrade to the latest version and check if everything is working as expected [or not]. If not, that will be good if you can narrow down the problem to the exactly configuration that is leading to the problem.

**Comment by alexdavydov** [comment]
Hello @zimmerle. 

While running continuous reloads with libmodsec loaded as a dynamic module, stock modsecurity.conf and CRS3.0.2 loaded, I can see growing RES footprint. It doesn't happen with the same Nginx binary without ngx_http_modsecurity_module.so loaded.

# ps aux | grep nginx | grep -v grep | awk '{print $6}'
15344
16220
16220
# for i in {1..100}; do nginx -s reload; done
# ps aux | grep nginx | grep -v grep | awk '{print $6}'
33092
31156
31156

ModSecurity@04f7009980d6715749de697710a640fd54a32789, ModSecurity-nginx@a2a5858d249222938c2f5e48087a922c63d7f9d8

Configure options for libmodsecurity:
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/
usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-pcre=/usr/bin/pcre-config --with-curl=/usr/bin/curl-config

Default CentOS 7 CXXFLAGS: '-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'

ModSecurity - v2.9.0-912-g04f7009 for Linux

 Mandatory dependencies
   + libInjection                                  ....v2.9.0-912-g04f7009
   + SecLang tests                                 ....04f7009

 Optional dependencies
   + GeoIP                                         ....found v1.5.0
      -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.29.0
      -lcurl  ,  -DWITH_CURL
   + YAJL                                          ....found v2.0.4
      -lyajl  , -DWITH_YAJL
   + LMDB                                          ....not found
   + LibXML2                                       ....found v2.9.1
      -lxml2 -lz -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled

Nginx version is 1.11.10, configure options are pretty much the same as in Fedora package (https://src.fedoraproject.org/rpms/nginx/blob/master/f/nginx.spec), give or take an optional module.

Let me know if you need more information.

**Comment by victorhora** [comment]
Thanks for the info @alexdavydov.

I was able to reproduce it here. I ran some tests with Valgrind and is also flagging some memory leaks when ngx_http_modsecurity is loaded:

==34396== 41,879 (88 direct, 41,791 indirect) bytes in 1 blocks are definitely lost in loss record 704 of 711
==34396== 3,184,513 (6,952 direct, 3,177,561 indirect) bytes in 79 blocks are definitely lost in loss record 711 of 711
==34396== LEAK SUMMARY:
==34396==    definitely lost: 7,040 bytes in 80 blocks
==34396==    indirectly lost: 3,219,352 bytes in 863 blocks
==34396==      possibly lost: 115,576 bytes in 15 blocks
==34396==    still reachable: 199,722 bytes in 3,462 blocks
==34396==         suppressed: 0 bytes in 0 blocks

As of now I'm inclined to believe that the issue might be on the connector rather than libModSecurity. Will investigate a bit more.

**Comment by zimmerle** [comment]
Please check 1ad95254cd8caec4a0af83d01844fc3cc65f3ce7. There was a fixed at #1563 which is likely to fix this behavior as well.

**Comment by ozermetin** [comment]
> Please check 1ad9525. There was a fixed at #1563 which is likely to fix this behavior as well.
> 

This problem persists. We have the same kind of memory leak during reloads. We have an environment for you to replicate the same issue.

**Comment by zimmerle** [comment]
Hi @ozermetin,

Thanks for the report. Re-opening this issue.

**Comment by defanator** [comment]
@ozermetin @alexdavydov @AdamJacobMuller there is the PR that addresses some real leaks in nginx connector: https://github.com/SpiderLabs/ModSecurity-nginx/pull/80

Could you please apply the proposed patch and check whether it helps in your cases?

**Comment by vaLski** [comment]
Considering the fact that this issue appears only during reload and having in mind  that the initial reporter @AdamJacobMuller is having 3k+ rules this might be a duplicate  of an issue I also reported in https://github.com/SpiderLabs/ModSecurity/issues/1663 and tracked down. Please check if it is ok after applying https://github.com/SpiderLabs/ModSecurity/pull/1667/files

**Comment by victorhora** [comment]
@AdamJacobMuller 

Do you mind letting us know if you notice improvements taking
https://github.com/SpiderLabs/ModSecurity/issues/1663#issuecomment-379856117 into consideration?

Thanks.

**Comment by zimmerle** [comment]
It seems the problem was solved. Closing.

**Comment by averges** [comment]
I'm afraid I'm facing this problem. 
With only 1 vhost on a testing server with no load, for each reload, nginx's memory grows by 12392KB. On other server with 8 vhost each reload add more than 100MB. After weeks, nginx use huge amounts of ram.
To avoid OOM errors I have to restart nginx after a few reloads.

Server:
    ModSecurity - v3.0.4 (7e0bc2691727b8c75f74638cdc4d1c45a689a7b6) with ModSecurity-nginx v1.0.1 (https://github.com/SpiderLabs/ModSecurity-nginx/commit/63feb81785140d5a5dca564befb5c87ff22282de) and Modsecurity-crs 3.3/dev (https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/6ed306e1b9aa8784d5e9c3e19da54cc7e20eb113)
    nginx-1.17.4
    Ubuntu 18.04.1

**Comment by zimmerle** [comment]
Hi @averges, I am reopening the issue to do a further investigation.

**Comment by cocooma** [comment]
Hi all, I'm hitting the same issue. On every nginx reload the memory usage is increasing. Do you have any update on this matter?

**Comment by zimmerle** [comment]
@cocooma we are working on the branch v3/dev/phases. The configuration issues will be tackled there. I will let you know as soon as we manage to have it ok to be tested.

**Comment by zimmerle** [comment]
no longer an issue in v3.1-experimental.
