### ISSUE TITLE
ipMatchFromFile does not support comments in v3

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/ModSecurity#2554]
`ipMatchFromFile` supported `#`-comments in v2, this is not possible in v3 and just reports a generic error

**Comment by zimmerle** [comment]
Hi @tomsommer that is already fixed on v3/master. Yet to be released. For the reference 42a16c71cfb995bb2cd76dab02f6fe7aa6b596be

**Comment by tomsommer** [comment]
This is still broken in 3.0.7

Blank lines are ignored, but lines that begin with # still throw errors with `ipMatchFromFile`

The fix in #1645 only applied to `pmFromFile`?

@zimmerle

**Comment by feanorknd** [comment]
we need comments in the file ;)

**Comment by daveram** [comment]
Issues like this are what prevent large enterprises and vendors like most of my clients from moving to mod_security v3

Comments in the file are used to denote which ranges are for what, so others don't have to go looking them up separately or note them elsewhere if we had to put in a rule against specific ranges and what they represent

**Comment by martinhsv** [comment]
Hi all, thanks for re-raising this.

Per the observation by @tomsommer , this item appears to have been incorrectly closed since the fix for #1645 was for a different operator.

**Comment by martinhsv** [comment]
If anyone wants to try it out, I have created a pull request for this at #2839 .

I will tentatively plan to merge it within a few days.

**Comment by tomsommer** [comment]
@martinhsv any chance of getting this fix in a release?

**Comment by martinhsv** [comment]
@tomsommer ,

Since it has already been merged to v3/master, it will be in the coming v3.0.x release by default.

**Comment by tomsommer** [comment]
@martinhsv I meant can we get a release :)

**Comment by martinhsv** [comment]
Hello @tomsommer ,

There is a v3.0.x release tentatively planned for the near-ish future (let's call it 5-7 weeks).

In the meantime feel free to build from source. (Or are you in a position where the policy at your installation only allows use of official releases?)

**Comment by tomsommer** [comment]
@martinhsv built from source and this issue is indeed resolved. Found another issue though (#2877) :)

Thanks
