### ISSUE TITLE
Permission problems using Apache2 MPM ITK

### ISSUE THREAD

**Issue by derhansen** [SpiderLabs/ModSecurity#712]
With Apache2 MPM ITK, every virtual host can run under a separate uid and gid. Using Apache2 MPM ITK with ModSecurity results in some error entries in the audit log because of missing permissions.

The Problem is, that the DBM file can't be accessed/written, because the default permissions to the files are 0640. This results in the situation, that only one virtual host is able to initially write the DBM files (if they do not exist). All other virtual hosts are not able to read/write to the DB; files resulting in the following messages in the audit log

<pre>
Message: collections_remove_stale: Failed to access DBM file "/tmp//global": Permission denied
Message: collections_remove_stale: Failed to access DBM file "/tmp//ip": Permission denied
</pre>

When you set the DBM file world writeable, then the above errors are not logged any more and each virtual host can access the DBM file.

The audit log still shows the following error, which I was not able to reproduce/fix

<pre>
Message: Audit log: Failed to lock global mutex: Permission denied
</pre>

It seems there is a general problem when running virtual hosts as different users with mod MPM ITK or mod RUID, as the global mutex problem is already filed here https://github.com/SpiderLabs/ModSecurity/issues/454

It would be great if you could define **SecDataDir** also in the **VHOST scope** or if file permissions to all DBM files could be set in the configuration file. Also it would be great if the global mutex problem could be resolved.

If I can help debugging the global mutex problem, don't hesitate to contact me.

**Comment by shawnholt** [comment]
As of 4/27/2015 this issue is still not resolved.  Cpanel claims it is a SpiderLabs issue in this thread:
Hello,

Much of the issue is related to limitations with Mod_Security itself with regard to shared storage and handlers like Mod_ruid2 and MPM-ITK. It's not something that cPanel can really solve, but that being said, the case is still open in order to find the best possible way to avoid these types of issues for customers"
ref: https://forums.cpanel.net/threads/modsecurity-rule-processing-failed.453321

**Comment by bartoszg** [comment]
As for now 19/01/2016 the problem still remains. 

ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/ip": Permission denied 
ModSecurity: Geo Lookup: Failed to lock proc mutex: Identifier removed

**Comment by sydro** [comment]
same problem here with mod_ruid2

**Comment by sydro** [comment]
Add patch in @ju5t comment [[link]](https://gist.github.com/ju5t/0d61ee80b23f0987d65e), then recompile and it works! 

My configuration was:
- ubuntu 14.04.4
- apache 2.4.7-1ubuntu4.11
- libapache2-mod-ruid2  0.9.8-3 
- libapache2-mod-security2 2.7.7-2 (rebuilded)

**Comment by shawnholt** [comment]
Its a shame that now CPANEL is forcing you to disable modsec if you want to use ruid2 or itk due to this bug that they claim has not been addressed by Spiderlabs or others.  IMO this will open a gaping hole in security.  They refuse to even test the patch as they say it is not widely adopted yet.  I wonder if CPANEL is even watching this thread and hope the figure-pointing ends and a solution is developed.

**Comment by Spork-Schivago** [comment]
Ju5t,

Which problem does your patch fix?   The Geo Lookup: Failed to lock proc mutex: Identifier removed issue or the Failed to access DBM file "/var/cpanel/secdatadir/ip": Permission denied  issue?   Thanks!

**Comment by Ogy** [comment]
bump
my workaround is set all to 777 via cron_daily 
this is insane

**Comment by ju5t** [comment]
@Spork-Schivago it should solve the file permission denied issue. I know that the DirectAdmin control panel includes it in their ModSecurity implementation. I would assume that accounts for a reasonable number of servers.

We're using it ourselves too ever since 2014 and haven't seen any side effects.

**Comment by Spork-Schivago** [comment]
Thank you Ju5t.   Still no fix for the modruid2 issues though, correct?   So even with the patch, I still won't be able to use modruid2.

**Comment by ju5t** [comment]
@Spork-Schivago I wrote a patch for that too. I've raised a pull request for it but unfortunately it hasn't been accepted yet. See https://github.com/mind04/mod-ruid2/pull/8 for more details.

**Comment by zimmerle** [comment]
Marking @ju5t's patch to be discussed in our next team meeting. Candidate for v2.9.2. The date is was not set yet.

**Comment by Spork-Schivago** [comment]
Zimmerle,

Do you know if @ju5t's first patch is already implemented?   If not, does your team plan on discussing implementing both patches in v2.9.2?   Thanks!

**Comment by Rendername** [comment]
If anyone is interested. 
We use [this patch](https://gist.github.com/ju5t/0d61ee80b23f0987d65e) on hosting servers more 2 years, where total the number of users and sites >= 30000. Used this for apache2-itk and not found any problems all this time of use.

**Comment by Rod-Gomes** [comment]
Thanks @Rendername .
Do not have any updates on this issue yet?
It's been three years!

**Comment by Rendername** [comment]
@Rod-Gomes, Apparently not. In the main branch never no one sent a pull request, but this patch really solves problem as a minimum when using the apache itk.

**Comment by ju5t** [comment]
I've never sent in a pull request because I think it can be improved. In the end I'm not a C developer and my knowledge of Apache's internals is limited. I can raise a pull request if it helps. 

@zimmerle wrote in August that the patch would be up for discussion in version 2.9.2. This version isn't released yet. An update is more than welcome.

**Comment by pa-de-solminihac** [comment]
@ju5t your patch looks great, and would be really useful. I think you should raise a pull request!

**Comment by victorhora** [comment]
The global mutex is optional since 112ba45 (included in 2.9.2 release)

@ju5t I've pushed your patch as PR #1912. It's tagged for review for 2.9.3.

Thanks all for your contributions :)

**Comment by ju5t** [comment]
@victorhora awesome! Thanks!
